export const SET_ACCOUNT_SHOW_STATUS = 'SET_ACCOUNT_SHOW_STATUS'
export const SET_ACCOUNT = 'SET_ACCOUNT'
export const SET_ACCOUNT_LIST_STATUS = 'SET_ACCOUNT_LIST_STATUS'
export const SET_ACCOUNT_CREATE_STATUS = 'SET_ACCOUNT_CREATE_STATUS'
